# Import

In [1]:
#Import all of the library that we're going to use
import pandas as pd
import numpy as np
import tensorflow as tf

# Upload dataset

In [2]:
#Here we're upload our dataset
# In here we're going to use the "Data Instagram" and "Data Tiktok"
dataset_ig = pd.read_csv("https://raw.githubusercontent.com/fachrul-rh/influeHands-ML/main/Dataset/Instagram.csv")
dummy_ig = pd.read_csv("https://raw.githubusercontent.com/fachrul-rh/influeHands-ML/main/Dataset/Dataset%20User%20(Instagram).csv")

In [3]:
dummy_ig.head()

Nama  Food & Cooking  Fashion  Entertainment  Travel & Accomodation  \
0  BrandIG1              10        0              0                      0   
1  BrandIG2               0       10              3                      0   
2  BrandIG3               0        0             10                      0   
3  BrandIG4               1        0              0                     10   
4  BrandIG5               0        0              0                      0   

   Beauty  Healthcare  Technology  Automotive  Education  Sports  Finance  \
0       0           0           0           0          0       0        0   
1       0           0           0           0          0       0        0   
2       0           0           0           0          0       0        0   
3       0           0           0           0          0       0        0   
4      10           3           0           0          0       0        0   

   Tips & Trick About Career  
0                          0  
1                          0  
2                          0  
3                          0  
4                          0

# Build Model

## Preparing Dataset IG

In [4]:
#Select the data for category
kategori_ig = dataset_ig.iloc[:, 6:]
kategori_ig.head()

Food & Cooking  Fashion  Entertainment  Travel & Accomodation  Beauty  \
0               0        0              0                      0       0   
1               0        0              1                      0       0   
2               0        0              0                      0       0   
3               0        0              0                      0       0   
4               1        0              0                      0       0   

   Healthcare  Technology  Automotive  Education  Sports  Finance  \
0           0           0           0          1       0        0   
1           0           1           0          0       0        0   
2           0           0           0          1       0        0   
3           0           0           0          0       0        0   
4           0           0           0          0       0        0   

   Tips & Trick About Career  
0                          0  
1                          0  
2                          1  
3                          1  
4                          0

In [5]:
 #Change csv to np
kategori_ig_np = kategori_ig.to_numpy()
print(kategori_ig_np)
print(kategori_ig_np.shape)

[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]
(174, 12)


In [6]:
kategori_ig_np_trans = kategori_ig_np.transpose()

In [7]:
#Select the username data
nama_ig = dataset_ig.loc[: , "Username Instagram"]
nama_ig.head()

0        @sabdaps
1     @btr_alicee
2      @halohanie
3    @vinamuliana
4     @fadiljaidi
Name: Username Instagram, dtype: object

In [8]:
nama_ig_np = nama_ig.to_numpy()
print(nama_ig_np)
print(nama_ig_np.shape)

['@sabdaps' '@btr_alicee' '@halohanie' '@vinamuliana' '@fadiljaidi'
 '@anisarahim' '@aisyafputri' '@keanuagl' '@fiersabesari' '@btr_babyla'
 '@cnlulaby' '@inezkristanti' '@eatandtreats' '@greyspolii'
 '@feliciaputritjiasaka' '@pufflovaa' '@punipun7' '@jeremiahlakhwani'
 '@ernandaputra' '@sarahgibson21' '@jennyjusuf' '@gadgetins'
 '@ariefmuhammad' '@sumargodenny' '@tasyiiathasyia' '@tasyafarasya'
 '@ridhomsakti' '@riaricis1795' '@aprirokh_' '@cacatengker' '@miawaug'
 '@shitlicious' '@srl789' '@kristanto_pd' '@annisast' '@lestykejora'
 '@sheggario' '@jonathanend' '@sallytanudjaja' '@amrazing'
 '@b_channel_indonesia' '@attahalilintar' '@raniazzhr' '@lucintaluna'
 '@motomobitv' '@galanghendra55real' '@fitra.eri' '@iwanbanaranblog'
 '@gadgetboy.id' '@sabrinachairunnisa_' '@andhika.diskartes' '@mgdalenaf'
 '@dr.shindyputri_' '@wegodevindonesia' '@nexcarlos' '@pritaghozie'
 '@dr. tirta' '@jenniferbachdim' '@htanoko' '@gadgetempireid' '@junarsyi'
 '@najwashihab' '@autonetmagz' '@kenandgrat' '@

## Preparing Data Dummy User

In [9]:
user_brand = dummy_ig.iloc[:1, :]
print(user_brand)

       Nama  Food & Cooking  Fashion  Entertainment  Travel & Accomodation  \
0  BrandIG1              10        0              0                      0   

   Beauty  Healthcare  Technology  Automotive  Education  Sports  Finance  \
0       0           0           0           0          0       0        0   

   Tips & Trick About Career  
0                          0  


In [10]:
target_ig = dummy_ig.iloc[:1 , 1: ]
target_ig.head()

Food & Cooking  Fashion  Entertainment  Travel & Accomodation  Beauty  \
0              10        0              0                      0       0   

   Healthcare  Technology  Automotive  Education  Sports  Finance  \
0           0           0           0          0       0        0   

   Tips & Trick About Career  
0                          0

In [11]:
#change csv to numpy
target_ig_np = target_ig.to_numpy()
print(target_ig_np)
print(target_ig_np.shape)

[[10  0  0  0  0  0  0  0  0  0  0  0]]
(1, 12)


In [12]:
brand_ig = dummy_ig.iloc[0:1 , 0:1]
brand_ig.head()

Nama
0  BrandIG1

In [13]:
#change csv to numpy
brand_ig_np = brand_ig.to_numpy()
print(brand_ig_np)
print(brand_ig_np.shape)

[['BrandIG1']]
(1, 1)


## Build Model

In [14]:
#create a list that contain a category on ig dataset
campaign_type = ["Food & Cooking", "Fashion", "Entertainment", "Travel & Accomodation", "Beauty", "Healthcare", "Technology", "Automotive", "Education", "Sports", "Finance", "Tips & Trick About Career"]
print(campaign_type)

['Food & Cooking', 'Fashion', 'Entertainment', 'Travel & Accomodation', 'Beauty', 'Healthcare', 'Technology', 'Automotive', 'Education', 'Sports', 'Finance', 'Tips & Trick About Career']


In [15]:
#create a variable that contain a len
len_dummy_ig = len(dummy_ig)
len_dataset_ig = len(dataset_ig)
len_campaign_type = len(campaign_type)
max_recommendation = 5

len_user_brand = len(user_brand)

In [16]:
target_ig_np_type = tf.constant(target_ig_np, dtype=tf.float32)
kategori_ig_np_trans_type = tf.constant(kategori_ig_np_trans, dtype=tf.float32)
print(target_ig_np_type)
print(kategori_ig_np_trans_type)

tf.Tensor([[10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]], shape=(1, 12), dtype=float32)
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 1. 0.]], shape=(12, 174), dtype=float32)


In [17]:
np.save("ig.npy", kategori_ig_np_trans_type.numpy())

In [18]:
#mengalikan target_ig_np_type dan kategori_ig_np_trans_type agar menjadi variable baru
target_kategori_ig_np_type = tf.matmul(target_ig_np_type, kategori_ig_np_trans_type)
print(target_kategori_ig_np_type)

tf.Tensor(
[[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0. 10.  0. 10.  0.  0. 10.  0.  0.
   0.  0.  0.  0.  0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.  0.
  10.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0. 10.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10. 10. 10. 10.
  10. 10. 10. 10.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]], shape=(1, 174), dtype=float32)


In [19]:
#mengalikan dengan bilangannya sendiri
target_kategori_ig_np_type_red = target_kategori_ig_np_type/tf.reduce_sum(target_kategori_ig_np_type, axis=1, keepdims=True)
print(target_kategori_ig_np_type_red)

tf.Tensor(
[[0.   0.   0.   0.   0.05 0.   0.   0.   0.   0.   0.05 0.   0.05 0.
  0.   0.05 0.   0.   0.   0.   0.   0.   0.   0.   0.05 0.   0.   0.
  0.   0.   0.   0.   0.   0.05 0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.05 0.   0.   0.05 0.
  0.   0.   0.   0.   0.   0.   0.   0.05 0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.05 0.   0.05 0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.05 0.05 0.05 0.05
  0.05 0.05 0.05 0.05 0.   0.05 0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
  0.   0.   0.   0.   0.   0.  ]], shape=(1, 174), dtype=float32)


In [20]:
#mendapatkan top 5 dari tf
top_5 = tf.nn.top_k(target_kategori_ig_np_type_red, max_recommendation)[1]
print(top_5)

tf.Tensor([[ 4 10 12 15 24]], shape=(1, 5), dtype=int32)


In [21]:
#melihat top 5
for i in range(len_user_brand):
  x = [nama_ig_np[int(index)] for index in top_5[i]]
  print('{}: {}'.format(brand_ig_np[i], x))

['BrandIG1']: ['@fadiljaidi', '@cnlulaby', '@eatandtreats', '@pufflovaa', '@tasyiiathasyia']
