# Import

In [22]:
#Import all of the library that we're going to use
import pandas as pd
import numpy as np
import tensorflow as tf

# Upload dataset

In [23]:
#Here we're upload our dataset
#In here we're going to use the "Data Instagram" and "Data Tiktok"
dataset_tiktok = pd.read_csv("https://raw.githubusercontent.com/fachrul-rh/influeHands-ML/main/Dataset/TikTok.csv")
dummy_tiktok = pd.read_csv("https://raw.githubusercontent.com/fachrul-rh/influeHands-ML/main/Dataset/Dataset%20User%20(Tiktok).csv")

In [24]:
dummy_tiktok.head()

Nama  Food & Cooking  Fashion  Entertainment  \
0  BrandTiktok1              10        0              0   
1  BrandTiktok2               0       10              0   
2  BrandTiktok3               0        5             10   
3  BrandTiktok4               3        3              0   
4  BrandTiktok5               2        0              0   

   Travel & Accomodation  Beauty  Healthcare  Technology  Automotive  \
0                      0       0           0           0           0   
1                      0       0           0           0           0   
2                      0       0           0           0           0   
3                     10       0           0           0           0   
4                      3      10           0           0           0   

   Education  Sports  Finance  Tips & Trick About Career  
0          0       0        0                          0  
1          0       0        0                          0  
2          0       0        0                          0  
3          0       0        0                          0  
4          0       0        0                          0

# Build Model

## Preparing Dataset IG

In [25]:
#Select the data for category
kategori_tiktok = dataset_tiktok.iloc[:, 4:]
kategori_tiktok.head()

Food & Cooking  Fashion  Entertainment  Travel & Accomodation  Beauty  \
0               1        0              0                      0       1   
1               0        0              1                      0       0   
2               0        1              1                      0       0   
3               1        0              0                      0       0   
4               0        1              0                      0       0   

   Healthcare  Technology  Automotive  Education  Sports  Finance  \
0           0           0           0          0       0        0   
1           0           0           0          0       0        0   
2           0           0           0          0       0        0   
3           0           0           0          0       0        0   
4           0           0           0          0       0        0   

   Tips & Trick About Career  
0                          0  
1                          0  
2                          0  
3                          0  
4                          0

In [26]:
 #Change csv to np
kategori_tiktok_np = kategori_tiktok.to_numpy()
print(kategori_tiktok_np)
print(kategori_tiktok_np.shape)

[[1 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 1 0 0]]
(174, 12)


In [27]:
kategori_tiktok_np_trans = kategori_tiktok_np.transpose()

In [28]:
#Select the username data
nama_tiktok = dataset_tiktok.loc[: , "Username Tiktok"]
nama_tiktok.head()

0      @siscakohl
1        @7iprast
2     @fadiljaidi
3    @cheekykiddo
4          @mmvia
Name: Username Tiktok, dtype: object

In [29]:
nama_tiktok_np = nama_tiktok.to_numpy()
print(nama_tiktok_np)
print(nama_tiktok_np.shape)

['@siscakohl' '@7iprast' '@fadiljaidi' '@cheekykiddo' '@mmvia'
 '@dilanjaniyar_2' '@vmuliana' '@adamshawn19' '@thoriqhal' '@syarif.yosee'
 '@tamarajessica' '@yoo_tooo' '@greyspolii' '@sindi9rande' '@putrabrahms'
 '@aintyoursb' '@thsaurus' '@rezkiachyana' '@irnaayu27' '@helwabasheel'
 '@dhiarcom' '@jumadilmusa13' '@nadineplvn' '@buiramira' '@ilhambachtiarr'
 '@alpa.candy' '@m0nyetku' '@zahfirahfiraa_' '@felicia.tjiasaka'
 '@skincarebyjessi' '@timothyronald22' '@gadgetin' '@devvwies'
 '@cannyclau' '@akmalriadi' '@tarnandoete' '@pinkyruslie' '@aqilasheila'
 '@ceofort1s' '@tyasnastiti' '@coach.regina' '@sabrinamaidaaah'
 '@elikaboen_' '@aprirokh_' '@sobat_hape' '@pear.ling' '@aloeeveeraaaaa'
 '@dennis_SLL' '@hazellitaa' '@hungryfever' '@lovlavina' '@jscwijayaa'
 '@nadiatussaa' '@junarsyi' '@boim_lenno' '@wawxv' '@axeljeremy_'
 '@billy.abraham' '@alimtd7' '@alvionithaputri' '@jasminechennn'
 '@martinpraja' '@yuliabaltschun' '@madminyo' '@delonixsen' '@duniaaderai'
 '@ivana.harjadi' '@riffas

## Preparing Data Dummy User

In [30]:
user_brand = dummy_tiktok.iloc[:1, :]
print(user_brand)

           Nama  Food & Cooking  Fashion  Entertainment  \
0  BrandTiktok1              10        0              0   

   Travel & Accomodation  Beauty  Healthcare  Technology  Automotive  \
0                      0       0           0           0           0   

   Education  Sports  Finance  Tips & Trick About Career  
0          0       0        0                          0  


In [31]:
target_tiktok = dummy_tiktok.iloc[:1 , 1: ]
target_tiktok.head()

Food & Cooking  Fashion  Entertainment  Travel & Accomodation  Beauty  \
0              10        0              0                      0       0   

   Healthcare  Technology  Automotive  Education  Sports  Finance  \
0           0           0           0          0       0        0   

   Tips & Trick About Career  
0                          0

In [32]:
#change csv to numpy
target_tiktok_np = target_tiktok.to_numpy()
print(target_tiktok_np)
print(target_tiktok_np.shape)

[[10  0  0  0  0  0  0  0  0  0  0  0]]
(1, 12)


In [33]:
brand_tiktok = dummy_tiktok.iloc[0:1 , 0:1]
brand_tiktok.head()

Nama
0  BrandTiktok1

In [34]:
#change csv to numpy
brand_tiktok_np = brand_tiktok.to_numpy()
print(brand_tiktok_np)
print(brand_tiktok_np.shape)

[['BrandTiktok1']]
(1, 1)


## Build Model

In [35]:
#create a list that contain a category on ig dataset
campaign_type = ["Food & Cooking", "Fashion", "Entertainment", "Travel & Accomodation", "Beauty", "Healthcare", "Technology", "Automotive", "Education", "Sports", "Finance", "Tips & Trick About Career"]
print(campaign_type)

['Food & Cooking', 'Fashion', 'Entertainment', 'Travel & Accomodation', 'Beauty', 'Healthcare', 'Technology', 'Automotive', 'Education', 'Sports', 'Finance', 'Tips & Trick About Career']


In [36]:
#create a variable that contain a len
len_dummy_tiktok = len(dummy_tiktok)
len_dataset_tiktok = len(dataset_tiktok)
len_campaign_type = len(campaign_type)
max_recommendation = 5

len_user_brand = len(user_brand)

In [37]:
target_tiktok_np_type = tf.constant(target_tiktok_np, dtype=tf.float32)
kategori_tiktok_np_trans_type = tf.constant(kategori_tiktok_np_trans, dtype=tf.float32)
print(target_tiktok_np_type)
print(kategori_tiktok_np_trans_type)

tf.Tensor([[10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]], shape=(1, 12), dtype=float32)
tf.Tensor(
[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]], shape=(12, 174), dtype=float32)


In [38]:
np.save("tiktok.npy", kategori_tiktok_np_trans_type.numpy())

In [39]:
#mengalikan target_ig_np_type dan kategori_ig_np_trans_type agar menjadi variable baru
target_kategori_tiktok_np_type = tf.matmul(target_tiktok_np_type, kategori_tiktok_np_trans_type)
print(target_kategori_tiktok_np_type)

tf.Tensor(
[[10.  0.  0. 10.  0. 10.  0. 10. 10.  0. 10.  0. 10.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.  0. 10.  0.  0.  0.  0.
   0. 10.  0.  0.  0.  0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10.  0.  0.
   0.  0.  0.  0.  0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0. 10. 10.  0.
   0.  0.  0.  0.  0.  0.  0.  0. 10. 10. 10.  0.  0.  0.  0.  0. 10.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]], shape=(1, 174), dtype=float32)


In [40]:
#mengalikan dengan bilangannya sendiri
target_kategori_tiktok_np_type_red = target_kategori_tiktok_np_type/tf.reduce_sum(target_kategori_tiktok_np_type, axis=1, keepdims=True)
print(target_kategori_tiktok_np_type_red)

tf.Tensor(
[[0.04545455 0.         0.         0.04545455 0.         0.04545455
  0.         0.04545455 0.04545455 0.         0.04545455 0.
  0.04545455 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.04545455
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.04545455 0.
  0.         0.04545455 0.         0.         0.         0.
  0.         0.04545455 0.         0.         0.         0.
  0.         0.04545455 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.04545455 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         

In [41]:
#mendapatkan top 5 dari tf
top_5 = tf.nn.top_k(target_kategori_tiktok_np_type_red, max_recommendation)[1]
print(top_5)

tf.Tensor([[0 3 5 7 8]], shape=(1, 5), dtype=int32)


In [42]:
#melihat top 5
for i in range(len_user_brand):
  x = [nama_tiktok_np[int(index)] for index in top_5[i]]
  print('{}: {}'.format(brand_tiktok_np[i], x))

['BrandTiktok1']: ['@siscakohl', '@cheekykiddo', '@dilanjaniyar_2', '@adamshawn19', '@thoriqhal']
